---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(gridExtra)
```

123
```{r}
sushi_review <- read_csv('sushi_review.csv')
sushi <- read_csv('sushi.csv')

sushi_review_select <- sushi_review %>% select(stars, text)
```

```{r}
sushi_tuna <- sushi_review_select %>%
  mutate(group = case_when(grepl("tuna", text) ~ "yes",
                           !grepl("tuna", text) ~ "no")) #%>%
```

```{r}
sushi_tuna2 <- sushi_tuna %>%
  group_by(stars, group) %>%
  summarize(n=n()) %>%
  mutate(freq=n/sum(n))
```

```{r}
sushi_tuna2 %>%
  filter(group == "yes") %>%
  ggplot(aes(x=stars, y=freq)) +
    geom_col()
```
123
```{r}
sushi_type <- c('tuna', 'salmon', 'scallop', 'shrimp', 'halibut' ,'clam')
plots <- list()
for (s in sushi_type){
  sushi_filter <- sushi_review_select %>%
    filter(grepl(paste('(?i)',s,sep=""), text))

  plots[[s]] <- ggplot(sushi_filter, aes(stars)) +
    geom_bar() +
    labs(title = s)
}

grid.arrange(grobs=plots, ncol=3)
```
Why they all have the left tail?

```{r}
sushi_type_j <- c('katsuo|maguro|ahi', 'sake', 'hotate', 'ebi', 'engawa', 'hokkigai|akagai|tsubugai|mirugai')
plots2 <- list()
for (s in sushi_type_j){
  sushi_filter <- sushi_review_select %>%
    filter(grepl(paste('(?i)',s,sep=""), text))

  plots2[[s]] <- ggplot(sushi_filter, aes(stars)) +
    geom_bar() +
    labs(title = s)
}

grid.arrange(grobs=plots2, ncol=3)
```
```{r}
sushi_filter <- sushi_review_select %>%
  filter(grepl(paste('(?i)','tuna',sep=""), text)) %>%
  filter(grepl(paste('(?i)','salmon',sep=""), text))

ggplot(sushi_filter, aes(stars)) +
    geom_bar() +
    labs(title = 'tuna&salmon')
```

```{r}
sushi_type <- c('tuna', 'salmon', 'scallop', 'shrimp', 'halibut' ,'clam')
plots <- list()
for (s in sushi_type){
  sushi_filter <- sushi_review_select %>%
    mutate(group = case_when(grepl(s, text) ~ "yes",
                            !grepl(s, text) ~ "no")) %>%
    group_by(stars, group) %>%
    summarize(n=n()) %>%
    mutate(freq=n/sum(n)) %>%
    filter(group == "yes")
      

  plots[[s]] <- ggplot(data=sushi_filter, aes(x=stars, y=freq)) +
    geom_col() +
    labs(title = s)
}

grid.arrange(grobs=plots, ncol=3)
```
